'use client';

import { useState } from 'react';
import { createOrder } from '../../../actions/order-actions';
import { ActionMessage } from '../../../../components/action-message';

type Item = { sku: string; description: string; quantity: number };

export function OrderForm({ buyers, drivers }: { buyers: { id: string; name: string | null; email: string }[]; drivers: { id: string; name: string | null }[] }) {
  const [items, setItems] = useState<Item[]>([{ sku: '', description: '', quantity: 1 }]);
  const [message, setMessage] = useState<{ success: boolean; error?: string } | null>(null);
  return <form className="space-y-6 rounded-2xl bg-white p-6 shadow-sm" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); form.set('items', JSON.stringify(items)); const result = await createOrder(form); setMessage(result); if (result.success) { event.currentTarget.reset(); setItems([{ sku: '', description: '', quantity: 1 }]); } }}>
    <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Order reference<input className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" name="orderRef" required /></label><label className="text-sm font-semibold text-slate-700">Buyer<select className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 font-normal" name="buyerId" required><option value="">Select buyer</option>{buyers.map((buyer) => <option key={buyer.id} value={buyer.id}>{buyer.name ?? buyer.email}</option>)}</select></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Delivery address<textarea className="mt-2 min-h-24 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" name="deliveryAddress" required /></label><label className="text-sm font-semibold text-slate-700">Assign driver<select className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 font-normal" name="driverId"><option value="">Assign later</option>{drivers.map((driver) => <option key={driver.id} value={driver.id}>{driver.name ?? driver.id.slice(0, 8)}</option>)}</select></label></div>
    <div><div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">Items</h2><button className="text-sm font-semibold text-emerald-700" onClick={() => setItems([...items, { sku: '', description: '', quantity: 1 }])} type="button">+ Add item</button></div><div className="mt-3 space-y-3">{items.map((item, index) => <div className="grid gap-3 sm:grid-cols-[1fr_2fr_100px_auto]" key={index}><input className="rounded-lg border border-slate-300 px-3 py-2" placeholder="SKU" required value={item.sku} onChange={(event) => setItems(items.map((current, itemIndex) => itemIndex === index ? { ...current, sku: event.target.value } : current))} /><input className="rounded-lg border border-slate-300 px-3 py-2" placeholder="Description" required value={item.description} onChange={(event) => setItems(items.map((current, itemIndex) => itemIndex === index ? { ...current, description: event.target.value } : current))} /><input className="rounded-lg border border-slate-300 px-3 py-2" min="1" type="number" value={item.quantity} onChange={(event) => setItems(items.map((current, itemIndex) => itemIndex === index ? { ...current, quantity: Number(event.target.value) } : current))} />{items.length > 1 && <button className="text-sm text-red-700" onClick={() => setItems(items.filter((_, itemIndex) => itemIndex !== index))} type="button">Remove</button>}</div>)}</div></div>
    <button className="rounded-lg bg-emerald-700 px-5 py-2.5 font-semibold text-white hover:bg-emerald-800" type="submit">Create order</button><ActionMessage message={message} />
  </form>;
}